#!/bin/zsh
# Populate the InkBench iOS bundle inputs:
#  - BenchModels/: the compiled K-step models (from inklab/netime, compiled from
#    trace/*.mlpackage by xcrun coremlcompiler; see trace/unroll_graph.py and
#    trace/stencil_graph.py to regenerate them),
#  - Kernels.swift: the game's ink Metal kernels, extracted verbatim from
#    ../ink_kernels.metal, plus the two stencil kernels used by netime/metaltime.swift,
#    plus placementRow from netime/placement.swift.
set -e
cd "$(dirname "$0")"
rm -rf BenchModels && mkdir BenchModels
for stem in ink_unroll_128x256_j26_fp16 heat_128x256_s32_fp16 heat_128x256_s8_fp16 grayscott_128x256_s8_fp16; do
  for k in 1 2 4 8; do cp -R ../netime/${stem}_u$k.mlmodelc BenchModels/; done
done
python3 - <<'PY'
src = open("../ink_kernels.metal").read()
lo = src.index("struct InkSplatG")
z = src.index("kernel void ink_zero", lo)
hi = src.index("\n}\n", z) + 3
mt = open("../netime/metaltime.swift").read()
st = mt[mt.index('let stencilSrc = """') + len('let stencilSrc = """'):]
st = st[:st.index('"""')]
body = "#include <metal_stdlib>\nusing namespace metal;\n" + src[lo:hi] + st
pl = open("../netime/placement.swift").read()
pl = pl[pl.index("import CoreML\n") + len("import CoreML\n"):pl.index("#if !INKBENCH")]
open("Kernels.swift", "w").write(
    "// GENERATED by prepare.sh from ../ink_kernels.metal (ink kernels, verbatim),\n"
    "// ../netime/metaltime.swift (stencil kernels) and ../netime/placement.swift\n"
    "// (placementRow). Do not edit.\n"
    "import Foundation\nimport CoreML\n\n"
    'let benchKernelSource = #"""\n' + body + '\n"""#\n' + pl)
PY
echo "BenchModels: $(ls BenchModels | wc -l | tr -d ' ') models; Kernels.swift $(wc -l < Kernels.swift) lines"
